FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY prisma ./prisma/
RUN npx prisma generate

COPY . .

RUN mkdir -p uploads

CMD ["sh", "-c", "npx prisma migrate deploy && npm run prisma:seed || true && npm run start:dev"]
